services:
    proposal-app:
        image: proposal-app
        environment:
            spring.profiles.active: prod
        ports:
            -   8080:8080
        depends_on:
            rabbitmq:
                condition: service_healthy
            postgres:
                condition: service_started

    postgres:
        image: postgres:latest
        container_name: proposal-postgres
        environment:
            POSTGRES_DB: proposal
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
        ports:
            - "5432:5432"

    rabbitmq:
        image: rabbitmq:3-management
        container_name: my-rabbitmq
        healthcheck:
            test: rabbitmq-diagnostics -q ping
            timeout: 5s
            interval: 5s
            retries: 3
        ports:
            - 5672:5672
            - 15672:15672